// Code generated by "stringer -type=ValueType"; DO NOT EDIT

package main

import "fmt"

const _ValueType_name = "TypeEnumTypeStringTypeBoolTypeInteger"

var _ValueType_index = [...]uint8{0, 8, 18, 26, 37}

func (i ValueType) String() string {
	if i < 0 || i >= ValueType(len(_ValueType_index)-1) {
		return fmt.Sprintf("ValueType(%d)", i)
	}
	return _ValueType_name[_ValueType_index[i]:_ValueType_index[i+1]]
}
