// Code generated by "stringer -type=ValidateOption"; DO NOT EDIT

package schema

import "fmt"

const _ValidateOption_name = "OptionExperimentMapArrayCoercion"

var _ValidateOption_index = [...]uint8{0, 32}

func (i ValidateOption) String() string {
	if i < 0 || i >= ValidateOption(len(_ValidateOption_index)-1) {
		return fmt.Sprintf("ValidateOption(%d)", i)
	}
	return _ValidateOption_name[_ValidateOption_index[i]:_ValidateOption_index[i+1]]
}
