// Code generated by "stringer -type=ValueType"; DO NOT EDIT

package schema

import "fmt"

const _ValueType_name = "ValueUnknownValueStringValueBoolValueNumberValueMap"

var _ValueType_index = [...]uint8{0, 12, 23, 32, 43, 51}

func (i ValueType) String() string {
	if i < 0 || i >= ValueType(len(_ValueType_index)-1) {
		return fmt.Sprintf("ValueType(%d)", i)
	}
	return _ValueType_name[_ValueType_index[i]:_ValueType_index[i+1]]
}
